[features]
seeds = false
skip-lint = false
[programs.localnet]
blinders = "EDZae9LKkhuoRXfbL1JeR9tWeYtdnjd2v9RkWkpsGNj2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/admin1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
